# Permalinks
permalink:      /post/:title.html

# Setup
title:          haircut
subtitle:       on managing macs
paginate:       5
baseurl:        ""
url:            "https://haircut.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Matthew Warren
  url:
  email:

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
